### ISSUE TITLE
Directories are missing in the list on S3 backend

### ISSUE THREAD

**Issue by vroad** [fclairamb/ftpserver#103]
I ran ftpserver on S3 backend and found that I could only list files. Is this not implemented yet?

If I enter a directory path directly in FTP client, I could list files for that directory, but subdirectory is missing.

I built manually from cb048f857f340a06dc5fa51b0535eedcc17db1a3 .

I modified AWS session initialization code because it doesn't currently allow configuring credentials from EC2 metadata server. That's the only change I made to the server.

**Comment by vroad** [comment]
Ok, I've just found the cause of error. I'm currently using FileZilla as ftp client.
If directory timestamp is out of range of unix timestamp, Filezilla omits it from list output without warnings!
This can be easily fixed by changing `time.time{}` to `time.Unix(0, 0)`. I'll submit a pull request later.

**Comment by vroad** [comment]
Done. https://github.com/fclairamb/afero-s3/pull/96

**Comment by fclairamb** [comment]
Will close it as soon as [afero's v1.1.0](https://github.com/fclairamb/afero-s3/releases/tag/v0.1.1) is applied.
