### ISSUE TITLE
No way to turn off debug mode

### ISSUE THREAD

**Issue by vroad** [fclairamb/ftpserver#104]
The server prints all command sent to it, and PASS command is no exception. Since debug mode is always on and not configurable, it's not possible to turn this off without editing source code.

And if I turn off debug mode by removing this line, the server does not log anything except for connected and disconnected events. Ideally, I would live the server to log about uploaded files.

https://github.com/fclairamb/ftpserver/blob/368c6cef3ca2497392178d17eba9e82475805423/server/server.go#L72

**Comment by fclairamb** [comment]
@vroad this should be fixed with #122. Tell me what you think about this.
