### ISSUE TITLE
 How to set the permissions for each user,

### ISSUE THREAD

**Issue by YANGY8365** [fclairamb/ftpserver#1148]
such as restricting users to only have read-only permissions and not being able to upload or delete.

**Comment by fclairamb** [comment]
Read-only access is documented [here](https://github.com/fclairamb/ftpserver/tree/main/fs#read-only).

If you need a fully-featured server please prefer [sftpgo](https://github.com/drakkan/sftpgo) which also supports FTP and is based on the same [ftpserverlib](https://github.com/fclairamb/ftpserverlib).
