### ISSUE TITLE
support show ip

### ISSUE THREAD

**Issue by newyorkthink** [fclairamb/ftpserver#1162]
![image](https://github.com/fclairamb/ftpserver/assets/87791643/64b55541-d8a9-4760-86ce-8c925f749b08)

when I use this command, it not show ip
i must use second command to show ip with ifconfig

so, don't use two command ,just only use fptserver command

**Comment by fclairamb** [comment]
This is the listening/binding address, which means "any IP".

In other words, you could connect to a new network (plug an ethernet cable), receiving a new IP address and it would still listen to it.
