### ISSUE TITLE
Please publish the newest version to Dockerhub!

### ISSUE THREAD

**Issue by nick-hf** [fclairamb/ftpserver#131]
https://hub.docker.com/r/fclairamb/ftpserver/

Looks like it's been a while! This server is incredibly useful, and I thank you much for it. It would be awesome if the latest version was containerized.

**Comment by fclairamb** [comment]
Sorry, I switched it to a separate docker hub repository because I wanted to separate credentials from other tools but I think my way of doing it is completely wrong and I will rework this part.

I need to:
- Use a builder image in the Dockerfile itself
- Compile it for different architectures

**Comment by fclairamb** [comment]
@nick-hf, this is all done!

You can run it with: 
```
docker run --rm -d -p 2121-2130:2121-2130 fclairamb/ftpserver
```
