### ISSUE TITLE
Remote connection problem

### ISSUE THREAD

**Issue by gabif9** [fclairamb/ftpserver#173]
I run the ftpserver service with Docker using the example ftpserver.json configuration.
With the local cli examples of uploading & downloading a jpeg image, it works perfect. I see that the image is saved in the /tmp folder inside the container.

But I can't access FTP using remote "softwares" like telnet, Cyberduck, Filezilla, or Google Chrome (ftp://).
I tried to re-install the container several times, but the error persists.

It seems that it doesn't recognize remote location and tries to connect locally when you want to fetch the list.

```
gabriel@gf-debian:~$ docker ps
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                   NAMES
06b1859199c5        fclairamb/ftpserver   "/bin/ftpserver"    12 hours ago        Up 8 minutes        0.0.0.0:2121->2121/tcp, 2122-2130/tcp   eloquent_raman
```

Local CLI example, works:
```
gabriel@gf-debian:~/Downloads$ ls -l | grep kitty
-rw-r--r--  1 gabriel gabriel    254776 Dec  7 10:36 kitty2.jpg
-rw-r--r--  1 gabriel gabriel    254776 Dec  7 10:36 kitty.jpg
```

From remote PC:
```
gabriel@Gabriels-MacBook-Pro ~ % telnet 10.20.23.23 2121
Trying 10.20.23.23...
Connected to debian.gf.
Escape character is '^]'.
220 ftpserver
USER test
331 OK
PASS test
230 Password ok, continue
CWD /
250 CD worked on /
PASV
227 Entering Passive Mode (172,17,0,2,8,77)
NLST /
425 Unable to open transfer: accept tcp [::]:2125: i/o timeout
```

Filezilla & Cyberduck errors:

<img width="610" alt="Screen Shot 2020-12-07 at 10 44 05 AM" src="https://user-images.githubusercontent.com/65986408/101358160-39fcd000-3879-11eb-9b4a-01d35709aabd.png">

<img width="1185" alt="Screen Shot 2020-12-07 at 10 46 09 AM" src="https://user-images.githubusercontent.com/65986408/101358295-6ca6c880-3879-11eb-8567-1be41d6ce3b6.png">

**Comment by fclairamb** [comment]
Hi @gabif9,

That's quite interesting, I never faced that issue before but it's real one.

What happens here is that:
- `PASV` works by sending the server address. As such to use it, you'll need to define a `listen_address` at the root of `ftpserver.json` file.
- `EPSV` doesn't require to specify an IP Address but [FileZilla only uses ESPV when you're in IPv4](https://superuser.com/a/1468116/465756). And you can't force it, there's [a request for this feature](https://trac.filezilla-project.org/ticket/10301) though.

I think I will add a `LISTEN_ADDRESS` environment variable (that will behave like the `listen_address` config) so that the docker example can easily work.

**Comment by gabif9** [comment]
Hi @fclairamb , thanks for your reply.

I try the json attr like you said and it doesn't work. The server fails to start.
Log:

```level=error ts=2020-12-09T22:47:27.206268939Z caller=server.go:132 component=server err="listen tcp 10.25.0.11:2121: bind: cannot assign requested address" event="Cannot listen"
--
```

```
{
  "version": 1,
  "accesses": [
    {
      "user": "test",
      "pass": "test",
      "fs": "os",
      "params": {
        "basePath": "/tmp"
      }
    }
  ],
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  },
  "listen_address": "10.25.0.11:2121"
}
```

Also , I check the code and if I am not wrong, that variable refers to the IP&port that will listen, is it correct?

Regards,

**Comment by fclairamb** [comment]
You're fast !

It seems like you read my answer before I realized I mixed up the `ListenAddres` which is the port listening address on the local interfaces and the `PublicPort` which is the IP address that the server will declare listening to.

So, I added:
- a `public_host` config
- a `PUBLIC_HOST` environment variable

You can test the proposal I made in #184 that way:
```bash
docker run --rm -ti -p 2121-2130:2121-2130 -e PUBLIC_HOST=10.25.0.11 fclairamb/ftpserver:pr-184
```

I will merge this PR and do a new release quite soon. I'd like to test the Google Drive integration prior to that.

**Comment by fclairamb** [comment]
This was fixed and will be present in the next release.
