### ISSUE TITLE
incorrect key of map

### ISSUE THREAD

**Issue by tennuem** [fclairamb/ftpserver#257]
Hi.
I can't to connect to sftp server, because key of map isn't correct. Need change par["usename"] > par["username"]
https://github.com/fclairamb/ftpserver/blob/master/fs/sftp/sftp.go#L30

**Comment by tennuem** [comment]
https://github.com/fclairamb/ftpserver/pull/258

**Comment by fclairamb** [comment]
Thank you for fixing this !
