### ISSUE TITLE
TLS Configuration Options

### ISSUE THREAD

**Issue by cstranex** [fclairamb/ftpserver#358]
There doesn't seem to be a way in the configuration to specify any configuration options for TLS for the FTP Server

**Comment by fclairamb** [comment]
Hi @cstranex,

Indeed,

- [The settings](https://github.com/fclairamb/ftpserver/blob/master/config/confpar/confpar.go) don't mention any TLS setting
- [The TLS setup](https://github.com/fclairamb/ftpserver/blob/master/server/server.go#L173-L175) is not implemented.

So yes, nothing exists at this stage. What are you interested in?

**Comment by cstranex** [comment]
I was looking for AUTH TLS support specifically

**Comment by cstranex** [comment]
Yeah, that is enough for the use we need :)

**Comment by fclairamb** [comment]
Hi @cstranex & @fuwn please tell me if you like the #392.
