### ISSUE TITLE
SFTP Issue - command=SSH-2.0-PUTTY_SNAPSHOT_2020_10_10.6538308 event="Unknown command"

### ISSUE THREAD

**Issue by windowshopr** [fclairamb/ftpserver#972]
Just found this repo and looking to get this setup on my local network.

This is my current config file:

```
{
  "version": 1,
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  },
  "accesses": [
    {
      "user": "test",
      "pass": "test",
      "fs": "os",
      "params": {
        "basePath": "/"
      }
    },
    {
      "user": "sftp",
      "pass": "sftp",
      "fs": "sftp",
      "params": {
        "user": "sftp2",
        "pass": "sftp2",
        "hostname": "192.168.68.103:22",
      }
    }
  ]
}
```

As you see, I have an accessor for vanilla FTP and an accessor for SFTP. My server's local IP address is 192.168.68.105, and I'm trying to connect to the server via my iPhone's FTPManager Pro version app. The parameters I've set in the app look like this for the SFTP connection:

![image2](https://user-images.githubusercontent.com/40477419/225805215-767d9be0-ee77-4391-9263-85005fc375fa.png)

(Sorry, the port should say 2121 for reproducibility, not 22)

When I try to connect to the server, the log says this:

```
level=debug component=server clientId=5 clientIp=192.168.68.103:64823 event="Client connected"
level=info component=driver clientId=5 remoteAddr=192.168.68.103:64823 nbClients=2 event="Client connected"
level=warn component=server clientId=5 command=SSH-2.0-PUTTY_SNAPSHOT_2020_10_10.6538308 event="Unknown command"
```

When I run the diagnose feature on the app, I see this output, which is good:

![image3](https://user-images.githubusercontent.com/40477419/225805439-675a4294-a615-47aa-8062-df63f59ad354.png)

So it sees the server and is able to communicate with it, but the server is rejecting some putty command? It makes me think I'm not setting up the params in the app or the config file correctly.

I've tried many combinations of username/password/port specifications in both the app and the config to no avail so far, so I'm opening it up here to see if I can get this figured out. I AM able to connect to the server via the app with the vanilla FTP parameters/config, but looking to switch to SFTP. Thanks!

**Comment by fclairamb** [comment]
You're mixing up SFTP and FTP/S. You should have a look [sftpgo](https://github.com/drakkan/sftpgo).
